### ISSUE TITLE
Support for the latest trunk code

### ISSUE THREAD

**Issue by Durimis** [komarios/FloorManager#1]
Hi komarios,
I was search for the floor plugin and run across your repository which seems was written for an earlier build and was wondering if you have a plan to update the code for latest build or point me at some direction. Thanks

**Comment by komarios** [comment]
Hi,
Unfortunately, I did not go through with the FloorManager project.My latest changes are uploaded to github, but I never finished what I was working on.
You are welcome to use the code as you like.I am not planning on working on FloorManager any more.
And I have no idea where the original project has gone since then.

Best Regards,
Kogias Marios
IT Professional
DBA, *nix Admin & Java DeveloperDevOps Enthusiast
  
|  
|    |  
Marios Kogias | LinkedIn
 
View Marios Kogias’ professional profile on LinkedIn. LinkedIn is the world's largest business network, help...
  | 
 |

  |

 





 

    On Saturday, June 20, 2020, 11:59:08 AM GMT+3, Joint Dots <notifications@github.com> wrote:  
 
 


Hi komarios,
I was search for the floor plugin and run across your repository which seems was written for an earlier build and was wondering if you have a plan to update the code for latest build or point me at some direction. Thanks

**Comment by Durimis** [comment]
Thanks for the reply :)
